// v:12.3.13
var skimlinks_domain = 'wordpress.redirectingat.com';
var skimlinks_legacy_support = true;
var skimlinks_cookie_sync_optout = true;
var skimlinks_audience_optout = true;
var skimlinks_dwell_tracking = false;
var skimlinks_first_party_na = false;
var skimwords_horizontal_distance = 80;
var skimwords_vertical_distance = 80;
var skimlinks_replace_timeout = 300;
var skimlinks_legacy_click_handlers = false;
var skimlinks_affiliate_unknown_links = true;
var noskimproducts = true;
var skimwords_instant = true;
if (typeof noskimwords === "undefined") {
var noskimwords = true;
}
var noskoupon = true;
var skimlinks_pub_id = '725X1342';

(function(h){var Fc,Gc,va,aa;aa=function(){var a,b,c,d,e,f,i,k,g,h,m,l,t,w,p,n,o,q;if(aa)return aa;d=function(a){return((null!=a?a[0]:void 0)||2)*{minutes:60,hours:3600,days:86400}[(null!=a?a[1]:void 0)||"days"]};n=[{label:"lotame",url:"//bcp.crwdcntrl.net/5/c=7507/pv=y?https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dlotame%26skim_mapping%3Dtrue%26provider_id%3D%24%7Bprofile_id%7D",resyncAfter:[6,"days"],priority:1,active:!0},{label:"blue_kai",url:"https://stags.bluekai.com/site/27381?redir=https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dblue_kai%26skim_mapping%3Dtrue%26provider_id%3D%24_BK_UUID",
resyncAfter:[1,"days"],priority:2,active:!0},{label:"dfp",url:"//cm.g.doubleclick.net/pixel?google_nid=skimlinks_ddp&google_cm",resyncAfter:[5,"days"],priority:2,active:!0},{label:"tapad",url:"//x.skimresources.com/?provider=tapad",resyncAfter:[3,"days"],priority:2,active:!0},{label:"mediamath",url:"//pixel.mathtag.com/sync/img?redir=https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dmediamath%26skim_mapping%3Dtrue%26provider_id%3D%5BMM_UUID%5D%26provider_dc%3D%5BMT_DC%5D",resyncAfter:[3,"days"],priority:2,
active:!0},{label:"app_nexus",url:"https://secure.adnxs.com/getuid?https%3A%2F%2Fx.skimresources.com%2F%3Fprovider_id%3D%24UID%26provider%3Dapp_nexus%26skim_mapping%3Dtrue",resyncAfter:[6,"days"],priority:2,active:!0},{label:"magnetic",url:"//magnetic.t.domdex.com/sync/skimlinks",resyncAfter:[7,"days"],priority:2,active:!0},{label:"exelate",url:"//loadeu.exelator.com/load/?p=787&g=001&j=0",resyncAfter:[7,"days"],priority:2,active:!0},{label:"krux",url:"//x.skimresources.com/?provider=krux",resyncAfter:[2,
"days"],priority:3,active:!0},{label:"add_this",url:"https://su.addthis.com/red/usync?pid=11179&url=https%3A%2F%2Fx.skimresources.com%2F%3Fprovider_id%3D%7B%7Buid%7D%7D%26provider%3Dadd_this%26skim_mapping%3Dtrue",resyncAfter:[2,"days"],priority:3,active:!0},{label:"skim",url:"//x.skimresources.com/?provider=skim",resyncAfter:[5,"days"],priority:3,active:!0}];k={};b=function(a,b){var c,d,e,f;if(a.filter)return null!=(c=a.filter)?"function"===typeof c.call?c.call(a,b):void 0:void 0;d=[];for(c=e=0,
f=a.length;0<=f?e<f:e>f;c=0<=f?++e:--e)b(a[c])&&d.push(a[c]);return d};h=function(a){k.syncCheck=a[0];k.getCookieSyncInfo=a[1];k.getServerTime=a[2];return k};t=function(a,b,c){return Boolean(a.timestamp+d(b.resyncAfter)<=c)};q=function(a){return k.getServerTime(function(b){var c;c=g(a,b);return setInterval(function(){if(c.length)return i(c.shift())},200)})};p=function(a,b){var c;c=Math.max(1,Number(a.priority))-1;null==b[c]&&(b[c]=[]);return b[c].push(a)};o=function(a){var b,c,d,e;for(c=a.length;c;)d=
Math.floor(Math.random()*c--),b=c,e=a[b],a[b]=a[d],a[d]=e;return a};g=function(a,c){var d,e,f,i,k;d=b(n,function(b){var d;return!b.active?!1:(d=a[b.label])?t(d,b,c):!0});e=[];f=b(d,function(a){return 1===a.priority});d=f.length?f:d;for(i=0,k=d.length;i<k;i++)f=d[i],p(f,e);f=[];for(i=0,k=e.length;i<k;i++)d=e[i],null!=d&&f.push.apply(f,o(d));return f};m=function(a){return q(w(a))};w=function(a){var b,c,d,e,f;d={};if(!a)return d;f=a.split("|");for(a=0,e=f.length;a<e;a++)b=f[a],b=b.split(":"),c=b[0],
d[c]={label:c,timestamp:parseInt(b[1])};return d};l=function(a){a.width=0;a.height=0;return a.style.display="none"};e=function(a,b){var c;null==b&&(b=j);c=b.createElement("img");c.src=a;c.width=1;c.height=1;return c};a=function(a,b){var c;null==b&&(b=j);null!=(c=b.getElementsByTagName("body")[0])&&c.appendChild(a);return a};c=null;f=function(){var b;c=b=c||a(j.createElement("iframe"));l(b);return b.contentDocument||b.contentWindow.document};i=function(b){var c;c=f();return a(e(b.url,c),c)};return{init:function(){h(arguments);
if(k.syncCheck())return k.getCookieSyncInfo(m)},__private__:{day:86400,isTimeToSync:t,configToSeconds:d,parseSyncCookie:w,getSuitableProviders:g,setProviders:function(a){return n=a}}}}();var X,Hc,Ic,ba,Jc,Kc,Nb,m,s,Ob,wa,Pb,Qb,Rb,Na,Oa,Lc,hb,Mc,Nc,Sb,Tb,j,o,Pa,Ub,ib,x,n,y,Vb,S,ca,xa,da,jb,ya,ea,za,Aa,Oc,q,Ba,Qa,Wb,kb,fa,ga,Pc,Qc,g,Rc,Ca,Sc,Tc,lb,Y,Uc,Vc,Ra,ha,Xb,Wc,Xc,Yc,Zc,Sa,I,$c,mb,ia,Yb,nb,Ta,ja,ka,la,Zb,ob,Ua,ad,Va,Da,bd,Wa,$b,ma,ac,cd,r,dd,bc,ed,pb,Xa,fd,Ya,gd,cc,Za,qb,hd,dc,rb,id,ec,fc,jd,
sb,gc,K,hc,ic,jc,T,kc,tb,lc,ub,mc,nc,na,vb,oc,N,$a,wb,J,Z,Ea,xb,pc,ab,yb,zb,Ab,Bb,Cb,U,bb,Fa,Db,F,Ga,A,B,oa,qc,L,kd,Eb,ld,cb,md,G,rc,sc,nd,Fb,tc,uc,V,v,u,Gb,vc,wc,Ha,pa,O,M,db,qa,Ia,ra,C,D,xc,H,od,z,pd,P,yc,E={}.hasOwnProperty,sa=[].indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(b in this&&this[b]===a)return b;return-1};da=jb=null;"undefined"!==typeof skimlinks_context_window&&null!==skimlinks_context_window&&(h=h[skimlinks_context_window]);j=h.document;ya=/http:/g;n=function(){return function(){var a;
a=navigator.userAgent.toLowerCase();a=/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||0>a.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(a)||[];return{browser:a[1]||"",version:parseFloat(a[2])||0}}}(this)();fa=[];ga=[];q={};Wb=(new Date).getTime();Ba=[];Oc=["buy.itunes.apple.com","itunes.apple.com","itunes.com"];kb={"t.umblr.com":{name:"z"}};ea=S=null;Qa=xa=!1;za=[];ca=[];Aa=[];y={domains:[]};x={};U=B=Vb=null;N="";Ga=F=bb=$a=null;
na=[];Z=[];J=Db=ub=vb=ab=null;Ea=!1;pc="beginning";xb=[];A=oa=!1;mc="skimlinksApplyHandlers";tb=Fa=!1;yb=300;nc=oc=Bb=Ab=zb=Cb=lc=!1;sc=[];ra=qa=Ia=db=C=null;H=D=v="";M=u=0;Ha=wc=pa=uc=xc=!1;V=[];O=!0;vc=tc=!1;Gb=[];z=h.location;P="";X=!1;cb=null;Za={};Fb=[];cc=!1;Fc=["noskim","norewrite"];Gc="*.g.doubleclick.net,*mjxads.internet.com,*pgpartner.co.uk,*pgpartner.com,*pricegrabber.co.uk,*pricegrabber.com,*overture.com,*youtube.com".split(",");wb=function(){return!0};va=[];Ca=function(a){var b;b=j.createElement("a");
b.href=a;return L(b.hostname)};id=function(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)};Pc=function(){var a,b;a="";for(b=0;8>b;++b)a+=id();return a};g=function(){return function(a,b){return null!=h[a]?h[a]:null!=window[a]?window[a]:b}}(this);Jc=function(){var a;H=Pc();jb=null!=(a=j.getElementsByTagName("html"))?a[0]:void 0;za=g("skimlinks_included_classes",[]);ca=g("skimlinks_excluded_classes",[]);Aa=g("skimlinks_included_ids",[]);da=g("force_location")?Ca(g("force_location")):
z.hostname;B=g("skimlinks_tracking",!1);B=g("affiliate_tracking",B);U=g("skimlinks_site")||g("skimlinks_sitename")||!1;N=g("skimlinks_domain")?"http://"+g("skimlinks_domain"):"";$a=g("skimlinks_google",!1);bb=null!=$a?$a:"skimout";F=g("skimlinks_target",!1);Ga=g("sl_test",!1);g("skimlinks_cookie_sync",[]);na=g("skimlinks_exclude",[]);Z=g("skimlinks_include",[]);ab=g("skimlinks_noright",!1);vb=g("skimlinks_exrel",!1);ub=g("skimlinks_byrel",!1);Db=g("skimlinks_blocked_tag",!1);oa=g("skimlinks_revenue_forecast",
!1);Fa=g("skimlinks_strip_attribute",!1);tb=g("skimlinks_ad_images",!1);"number"===typeof g("skimlinks_replace_timeout")&&(yb=g("skimlinks_replace_timeout"));"boolean"===typeof g("skimlinks_before_click_handler")&&(lc=g("skimlinks_before_click_handler"));J=0;A=Xc();Cb=g("skimlinks_retargetting_trigger",!1);zb=g("skimlinks_retargetting_adv_id",!1);Ab=g("skimlinks_retargetting_pix_id",!1);Bb=!1;oc=g("skimlinks_first_party_na",!1);"undefined"!==typeof skimlinks_cookie_sync_optout&&null!==skimlinks_cookie_sync_optout&&
(nc=skimlinks_cookie_sync_optout);g("skimwords_live_scraping",!1);cc=g("skimlinks_url_extraction_rules",!1);h.skimlinks_revenue_forecast=window.skimlinks_revenue_forecast=!1;C=g("skimlinks_pub_id","");if(g("skimlinks_legacy_support"))h.skimlinks=window.skimlinks=function(){return!0},g("mugicPopWin")&&(h._mugicPopWin=window._mugicPopWin=h.mugicPopWin),h.mugicPopWin=window.mugicPopWin=function(){return!0},h.mugicRight=window.mugicRight=function(){return!0},h.mugicRightClick=window.mugicRightClick=function(){return!0};
u=g("skimlinks_dnt",0);M=g("skimlinks_nocookie",!1);M=g("skimlinks_nocookie",!1);db=g("noimpressions",!1);qa=g("noskimlinks",!1)||g("noskim",!1)||!1;O=g("skimlinks_legacy_click_handlers",!0);tc=g("skimlinks_affiliate_unknown_links",!1);qa&&($.skimlinks=!1);(Ia=g("noskimwords",!1)||g("noskim",!1)||!1)&&($.skimwords=!1);ra=g("nounlinked",!1)||g("noskim",!1)||!1;sc=g("unlinked_excludes",[]);ra&&($.unlinked=!1);xc=g("skim_toolbar",!1);uc=g("skimlinks_ajax_rerun",!1);g("skimlinks_editor",!1);wc=g("skimlinks_ipc",
!1);Ha=g("skimlinks_ipc_diy",!1);vc=g("skimlinks_dwell_tracking",!1);Gb=g("skimlinks_dwell_allowed_urls",[]);g("_merchantSettings")&&"undefined"===typeof replace_url_field?(pa=!0,mc="skimlinksApplyHandlersAlt"):pa=!1;Ea=g("skimlinks_ipc_decoration",!1);pc=g("skimlinks_ipc_position","beginning");xb=g("skimlinks_ipc_domain_whitelist",[]);if(h.document&&h.document.referrer)P=h.document.referrer;bd(da)&&(Ia=qa=!0);B&&!/^[a-z0-9_\\|]+$/i.test(B)&&(B=!1);if("undefined"!==typeof p&&null!==p)p.pag=l.pag=
g("force_location",z.href),p.pub=l.pub=C,p.uc=l.uc=B;"undefined"!==typeof assign_skimwords_globals&&null!==assign_skimwords_globals&&assign_skimwords_globals();ca.push("noskimlinks");ca.push("noskim");cb=j.createTextNode("").nodeName;return!0};pd=function(){return!nc};od=function(a,b){return a.hasOwnProperty(b)};Xc=function(){var a;return"function"===typeof(a=new Date).getTimezoneOffset?a.getTimezoneOffset():void 0};bd=function(a){var b,c,d,e;if(c=g("noskim_domains",!1))for(d=0,e=c.length;d<e;d++)if(b=
c[d],-1!==a.toLowerCase().indexOf(b.toLowerCase()))return!0;return!1};L=function(){return function(){var a;a=/^www\./i;return function(b){return b.replace(a,"")}}}(this)();s=function(){return function(){return j.addEventListener?function(a,b,c,d){null==d&&(d=!1);if(a&&(a.nodeName||a===h))return a.addEventListener(b,c,d)}:function(a,b,c){if(a&&(a.nodeName||a===h))return a.attachEvent("on"+b,function(){return 7>n.version&&!h.event?(setTimeout(function(){return c.call(a,h.event)},100),!0):c.call(a,h.event)})}}}(this)();
(function(){return function(){return j.createElement("div").getElementsByClassName?function(a,b){return I(a,b)?a:a.getElementsByClassName(b)}:function(a,b){var c;c=Rb(b);return Ub(a,c)}}})(this)();o=function(){return function(){var a,b;b=[function(){var b,d,e,f;e=[["%20","+"],["!","%21"],["'","%27"],["\\(","%28"],["\\)","%29"],["\\*","%2A"],["\\~","%7E"]];f=[];for(b=0,d=e.length;b<d;b++)a=e[b],f.push([RegExp(a[0],"g"),a[1]]);return f}()];return function(c){var d,e,c=encodeURIComponent(c);for(d=0,
e=b.length;d<e;d++)a=b[d],c=c.replace(a[0],a[1]);return c}}}(this)();Ua=function(){return function(){var a;a=/^\/\/|https?:\/\//i;return function(b,c){return a.test(b)&&(!c||!da||-1===c.indexOf(da))&&(!da||-1===da.indexOf("."+c))}}}(this)();m=function(a,b,c){var d;3<=arguments.length&&("undefined"!==typeof a.setAttribute?a.setAttribute(b,c):a[b]=c);try{return d=a[b],null==d&&(d=a.getAttribute(b)),d}catch(e){return null}};Oa=function(a,b,c){arguments[1]="data-"+b;return m.apply(this,arguments)};ld=
function(a,b){var c;c=a.innerText||a.textContent||a.nodeValue;if(2<=arguments.length)"undefined"!==typeof a.innerText?a.innerText=b:a.textContent=b,c=b;return c};mb=function(a){return(""+a).replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")};G=function(){return function(){var a,b;if(String.prototype.trim)return function(a){return null===a?"":String.prototype.trim.call(a)};a=/^\s+/;b=/\s+$/;/\S/.test("\u00a0")&&(a=/^[\s\xA0]+/,b=/[\s\xA0]+$/);return function(c){return null===
c?"":c.toString().replace(a,"").replace(b,"")}}}(this)();Hc=function(a,b){return!I(a,b)?(a.className+=" "+b,!0):!1};ed=function(a){var b,c,d,e,f;if("object"===typeof a||a instanceof Array){e="";d=0;c=a instanceof Array;for(f in a)E.call(a,f)&&(b=a[f],0<d&&(e+=","),c?e+=r(b):(b=r(b),e+='"'+f+'":'+b),d++);return c?"["+e+"]":"{"+e+"}"}return"string"===typeof a?(b=a.replace(/"/g,'\\"',a),'"'+b+'"'):isNaN(a)?"null":a.toString()};r=function(){return function(){var a;return"undefined"!==typeof JSON&&null!==
JSON&&JSON.stringify&&'["la"]'===JSON.stringify(["la"])?(a=JSON.stringify,function(b){return a(b)}):ed}}(this)();Pa=function(){return function(){var a,b;a=/[-[\]{}()*+?.,\\^$|#\s]/g;b=/\s+/g;return function(c){return c.replace(a,"\\$&").replace(b,"s+")}}}(this)();rb={topics:{},on:function(a,b){var c;if(null==(c=this.topics)[a])c[a]=[];return this.topics[a].push(b)},off:function(a,b){var c;c=0<=sa.call(this.topics[a],b);if(-1<c)return this.topics[a].splice(c,1)},once:function(a,b){var c;c=function(a){return function(){c.called||
b.apply(a,arguments);return c.called=!0}}(this);c.called=!1;return this.on(a,c)},publish:function(a,b){var c,d,e,f,i,k;c={topic:a,extra:b};if(this.topics[a]){i=this.topics[a];k=[];for(e=0,f=i.length;e<f;e++)d=i[e],k.push("function"===typeof d?d(c):void 0);return k}}};Rb=function(a){a=Pa(a);return RegExp("\\b"+a+"\\b","i")};I=function(a,b){return a.className?Rb(b).test(a.className):!1};Ub=function(a,b){var c,d,e,f,i;d=[];a.className&&b.test(a.className)&&d.push(a);i=a.childNodes;for(e=0,f=i.length;e<
f;e++)c=i[e],d=d.concat(Ub(c,b));return d};Wa=function(a){for(var b,c,d,e;a&&a!==jb;){c=a.id;for(d=0,e=za.length;d<e;d++)if(b=za[d],I(a,b))return!1;for(d=0,e=Aa.length;d<e;d++)if(b=Aa[d],c===b)return!1;for(c=0,d=ca.length;c<d;c++)if(b=ca[c],I(a,b))return!0;a=a.parentNode}return za.length||Aa.length?!0:!1};la=function(a,b,c){null==c&&(c=!1);for(b=RegExp("\\b(?:(?:"+Pa(b)+")|(?:noskim))\\b","i");null!=a&&a!==jb;){if(a.className&&b.test(a.className))return!0;a=c?null:a.parentNode}return!1};Pb=function(a,
b){var c,d,e,f,i,k,h;C||(C=g("skimlinks_pub_id",""));k=P?"&pref="+o(P):"";c=!1;0<b.indexOf("#slm-")&&(d=b.split("#slm-"),2===d.length&&!isNaN(d[1])&&10*parseInt(d[1])===10*d[1]&&(b=d[0],c=d[1]));e=m(a,"data-skimlinks-editor")&&1===parseInt(m(a,"data-skimlinks-editor"))?1:0;N||(N=g("skimlinks_domain")?"http://"+g("skimlinks_domain"):Na());I(a,"skimwords-link")?(h=m(a,"data-skimwords-word"),d=m(a,"data-skim-creative"),f=m(a,"data-skim-product"),i=g("skimlinks_domain")?"http://"+g("skimlinks_domain"):
Na(),"undefined"!==typeof settings&&null!==settings&&(i=settings.sw_domain||i),b=""+i+"/?id="+C+""+(B?"&xcust="+B:"")+""+(!1!==c?"&xs=9":"&xs=2")+"&url="+o(b)+"&xguid="+v+"&xuuid="+H+"&xsessid="+D+"&isjs=1&xword="+(h?h:"")+"&xcreo="+(d?d:"")+"&xpid="+(f?f:"")+"&xed="+e+"&sref="+o(z)+""+k+""+(u?"&dnt="+u:"")+""+(M?"&fdnt=1":"")+""+(!1!==c?"&slmcid="+c:"")+""+(!1!==A?"&xtz="+A:"")):I(a,"skimlinks-inline")?(d=m(a,"data-skim-creative"),b=""+N+"/?id="+C+""+(U?"&site="+U:"")+""+(Ga?"&test="+Ga:"")+""+(B?
"&xcust="+B:"")+""+(!1!==c?"&xs=9":"&xs=8")+"&isjs=1&url="+o(b)+"&xguid="+v+"&xuuid="+H+"&xsessid="+D+"&xcreo="+(a&&null!=d?d:0)+"&xed="+e+"&sref="+o(z)+"&pref="+o(P)+""+(u?"&dnt="+u:"")+""+(M?"&fdnt=1":"")+""+(!1!==c?"&slmcid="+c:"")+""+(!1!==A?"&xtz="+A:"")):la(a,"noskimlinks")||(d=m(a,"data-skim-creative"),b=""+N+"/?id="+C+""+(U?"&site="+U:"")+""+(Ga?"&test="+Ga:"")+""+(B?"&xcust="+B:"")+""+(!1!==c?"&xs=9":"&xs=1")+"&isjs=1&url="+o(b)+"&xguid="+v+"&xuuid="+H+"&xsessid="+D+"&xcreo="+(a&&null!=d?
d:0)+"&xed="+e+"&sref="+o(z)+""+k+""+(u?"&dnt="+u:"")+""+(M?"&fdnt=1":"")+""+(!1!==c?"&slmcid="+c:"")+""+(!1!==A?"&xtz="+A:""));X&&!la(a,"noskimlinks")&&(b+="&abp=1");return b};Sa=function(a){var b,c,d;if(tb)return!1;if(a.hasChildNodes()){d=a.childNodes;for(a=0,c=d.length;a<c;a++)if(b=d[a],b=Sa(b))return!0}else return Ta(a);return!1};Ta=function(a){var b,c,d,e,f;if(tb)return!1;b=[[300,250],[302,252],[304,254],[300,300],[302,302],[304,304],[468,60],[470,62],[472,64],[728,90],[730,92],[732,94]];if(a&&
a.nodeName&&"IMG"===a.nodeName.toUpperCase()){d=a.offsetWidth||0;c=a.offsetHeight||0;for(e=0,f=b.length;e<f;e++)if(a=b[e],d===a[0]&&c===a[1])return!0}return!1};lb=function(a){var b;b=a.target||a.srcElement;if(O&&b&&!b.href&&a.currentTarget)b=a.currentTarget;for(;b&&"A"!==b.nodeName.toUpperCase()&&"AREA"!==b.nodeName.toUpperCase();){if(Ta(b))return null;b=Ra(b)}return b};K=function(a){var b;b=lb(a);if(!b||Sa(b))return!0;fc(b);if(g("vglnk")&&I(b,"skimwords-link"))a&&a.stopPropagation?a.stopPropagation():
(a=h.event,a.cancelBubble=!0);return!0};Ra=function(a){for(;a.parentNode;){a=a.parentNode;if(Ta(a))break;if("A"===(null!=a?a.nodeName.toUpperCase():void 0)||"AREA"===(null!=a?a.nodeName.toUpperCase():void 0))return a}return null};kd=function(a){return a=v?a.replace(/([&\?]{1})xguid=([a-fA-F0-9]{32})/,"$1xguid="+v):a.replace(/([&\?]{1}xguid=[a-fA-F0-9]{32})/,"")};Qb=function(a,b){var c,d;d=a();if(null!=d)return function(a){return a(d)};c=null;rb.once(b,function(){return"function"===typeof c?c(a()):
void 0});return function(a){return c=a}};Sc=function(){var a;return null!=(a=va[0])?a.guid:void 0};Rc=Qb(function(){var a;return null!=(a=va[0])?a.csp:void 0},"beacon");Yc=Qb(function(){var a;return null!=(a=va[0])?a.ts:void 0},"beacon");fc=function(a){var b,c,d,e;d=!1;b=$a;a&&a.nodeName&&"A"!==a.nodeName.toUpperCase()&&"AREA"!==a.nodeName.toUpperCase()&&(a=Ra(a));if(a){e=Tc(a);N||(N=g("skimlinks_domain")?"http://"+g("skimlinks_domain"):Na());c=N;if(e.length>=c.length&&e.substr(0,c.length)===c)return!0;
if("msie"===n.browser&&a.childNodes.length&&3===a.childNodes[0].nodeType)d=a.innerHTML;c=-1!==e.indexOf(c)?e:Pb(a,e);b&&qd(e);gc(a);a.href=c;a.href=c;d&&a.innerHTML!==d&&setTimeout(function(){return function(){return a.innerHTML=d}}(this),yb)}return!0};Na=function(){var a;a="msie"===n.browser&&8>=n.version;return!Sc()&&!a?"//go.skimresources.com":"//go.redirectingat.com"};ma=function(a){return-1!==(N||Na()).indexOf(a)||-1!==a.indexOf("go.redirectingat.com")||-1!==a.indexOf("go.skimresources.com")};
Zb=function(a){return!0===x[a]||(null===x[a]||void 0===x[a])&&tc&&!ma(a)};Da=function(a){return oa?(Zb(a)&&(J+=1),!1):Zb(a)};gd=function(a){return a in kb};ac=function(a){var b,c;if(!Db)return!1;b=null!=a?a.previousSibling:void 0;if(!b)return!1;a=("["+Db+"]").toLowerCase();c=ld(b);if(!c)return!1;c=c.toLowerCase();c=G(c);b=c.lastIndexOf(a);return-1!==b&&b+a.length===c.length};ka=function(a){return!a||ub&&a===ub||!$c(a)};$c=function(a){var b,c,d,e;if(!a)return!1;b=a.toLowerCase().split(/\s+/);a=vb?
[vb.toLowerCase()]:[];a=a.concat(Fc);for(d=0,e=b.length;d<e;d++)if(c=b[d],0<=sa.call(a,c))return!0;return!1};Ob=function(){var a,b,c,d;S={};ea={};U&&na.push(U);d=na.concat(Gc);for(b=0,c=d.length;b<c;b++)a=d[b],S[a]=a.length;for(b=0,c=Z.length;b<c;b++)a=Z[b],ea[a]=a.length;return S};ob=function(a){var b,c,d;(null===S||null===ea)&&Ob();if(!a)return!1;for(b in S)if(E.call(S,b))if(c=S[b],0===b.indexOf("*")){if(b=b.substr(1),c-=1,d=a.lastIndexOf(b),-1!==d&&d===a.length-c)return!0}else if(a===b)return!0;
return!1};ad=function(a){var b,c,d;(null===S||null===ea)&&Ob();if(!a)return!1;if(0===Z.length)return!0;for(b in ea)if(E.call(ea,b))if(c="*"===b.substr(0,1),d="*"===b.substr(b.length-1,1),b=b.replace(/\*/g,""),c&&d){if(-1!==a.indexOf(b))return!0}else if(c){if(-1!==a.indexOf(b)&&a.indexOf(b)===a.length-b.length)return!0}else if(d){if(0===a.indexOf(b))return!0}else if(a===b)return!0;return!1};ja=function(a,b){return Ua(a,b)&&!ob(b)&&ad(b)};sb=function(a){if(O&&10>a)return Ba=jd(),setTimeout(function(){return sb(a+
1)},2E3*a)};jd=function(){var a,b,c,d,e,f,i;if(O){b={};d=[];c=[];for(e=0,f=Ba.length;e<f;e++)a=Ba[e],a.parentNode?c.push(a):b[a.href]=1;i=Y();for(e=0,f=i.length;e<f;e++)a=i[e],b[a.href]&&d.push(a);Nb(d,!1);return d.concat(c)}};Ic=function(a,b){var c,d,e;d=[];oa&&(a.xrf=1);for(c in a)E.call(a,c)&&(e=a[c],"data"!==c&&d.push(""+c+"="+e));a.data&&d.push("data="+a.data);return b+"?"+d.join("&")};md=function(a){var b,c;b=Ca(a);if(ma(b))return!0;b="";0<a.indexOf("#slm-")&&(c=a.split("#slm-"),2===c.length&&
!isNaN(c[1])&&10*parseInt(c[1])===10*c[1]&&(a=c[0],b=c[1]));a={call:"track",data:o('{"pubcode":"'+C+'", "referrer":"'+z+'", "pref":"'+P+'", "site":"'+U+'", "url":"'+a+'", "custom":"'+B+'", "xtz":'+A+', "uuid":"'+H+'", "slmcid":"'+b+'", "product":"1"}')};u&&(a.dnt=u);M&&(a.fdnt=1);a=Ic(a,"//t.skimresources.com/api/");a=a+"&rnd="+Math.random();Uc(a);return!0};gc=function(a){var b,c;if(!(null!==a&&a.sl_href_restore_scheduled))return b=a.href,c="msie"===n.browser&&7>n.version?1E4:yb,a.sl_href_restore_scheduled=
!0,setTimeout(function(){return function(){a.href=b;a.href=b;return delete a.sl_href_restore_scheduled}}(this),c)};Zc=function(a,b){var c,d;d=!1;c=kd(b);if(c!==b&&(a&&a.nodeName&&"A"!==a.nodeName.toUpperCase()&&"AREA"!==a.nodeName.toUpperCase()&&(a=Ra(a)),a)){if("msie"===n.browser&&a.childNodes.length&&3===a.childNodes[0].nodeType)d=a.innerHTML;gc(a);a.href=c;a.href=c;d&&a.innerHTML!==d&&setTimeout(function(){return function(){return a.innerHTML=d}}(this),300)}return c};hc=function(a,b){var c,d;qc(a);
F&&m(a,"target",F);d=m(a,"onclick");c="click"===b.type||"contextmenu"===b.type;if(null!=d&&-1!==d.toString().indexOf("return false")){if(c)return wb(a),dc(b)}else return wb(a),K(b)};qb=function(a){var b,c,d;b=lb(a);d=b.href;c=Ca(d);ma(c)&&(d=Zc(b,d));""===v&&oc?hc(b,a):md(d);return!0};Uc=function(a){var b,c;b=j.getElementsByTagName("body")[0];c=j.createElement("img");c.src=a;c.width=1;c.height=1;if("undefined"!==typeof c.style)c.style.display="none";b.appendChild(c);return c};ha=function(a,b,c,d,
e){var t;var f,i,k,g,h;null==c&&(c={});f=c.charset||null;h=c.target||null;t=null!=(i=c.async)?i:!0,c=t;i=null!=h&&h.document?h.document:j;k=i.getElementsByTagName("head")[0];g=i.createElement("script");g.type="text/javascript";if(f)g.charset=f;if(b)g.onload=g.onreadystatechange=function(a){return function(){var c;c=!1;return function(){var d;d=a.readyState;if(!c&&(!d||"complete"===d||"loaded"===d))return g.onload=g.onreadystatechange=null,c=!0,b.call(h),!0}}}(this)();g.onerror=function(){if(null!=
d)return null!=e?d(e):d(!1)};g.async=!1!==c;g.src=a;k.appendChild(g);return g};Y=function(a,b){var c,d,e,f,i,k;e=null;a&&(e=RegExp("\\b"+Pa(a)+"\\b","i"));k=[];b||(b=j);d=b.getElementsByTagName("a");for(f=0,i=d.length;f<i;f++){c=d[f];try{c.href&&(!e||c.className&&e.test(c.className))&&k.push(c)}catch(g){}}d=b.getElementsByTagName("area");for(f=0,i=d.length;f<i;f++){c=d[f];try{c.href&&(!e||c.className&&e.test(c.className))&&k.push(c)}catch(h){}}return k};Va=function(a){return-1!==a.indexOf("itunes.apple.com")||
-1!==a.indexOf("itunes.com")||-1!==a.indexOf("phobos.apple.com")?!0:!1};qc=function(a){var b,c,d;if(!Fa)return!1;for(c in Fa)if(od(Fa,c)&&(d=Fa[c],(b=m(a,c))&&0===b.indexOf(d)))b=b.substr(d.length),m(a,c,b);return!0};$b=function(a){return a&&Cb&&!Bb&&ia(""+a,Cb)};Nb=function(a,b){var c,d,e,f,i,k,g,h,j,l,t;null==b&&(b=!0);f=za.length||Aa.length||ca.length;k=[];d=0;for(l=0,t=a.length;l<t;l++)if(c=a[l],i=L(c.hostname),c.sl_hidden_domain&&(i=L(c.sl_hidden_domain)),j=G(c.href),Ua(j,i)){h=m(c,"rel");g=
m(c,"onclick");m(c,"sl-processed",1);c["sl-processed"]=1;e=Xb(j);$b(e)&&Tb(zb,Ab);if(b&&ja(j,i)&&(Da(i)?(d++,q.hasOwnProperty(j)?q[j].ae=1:q[j]={count:0,ae:1}):q.hasOwnProperty(j)||(q[j]={count:0,ae:0}),q[j].count++,e))q[j].slmcid=e,0>sa.call(V,e)&&V.push(e);J=d;if(!pa||!Va(j))if((!f||!Wa(c))&&!ac(c))Da(i)||Va(j)?(q.hasOwnProperty(j)&&(q[j].ae=1),ka(h)&&(qc(c),F&&m(c,"target",F),null!=g&&-1!==g.toString().indexOf("return false")?s(c,"click",dc):s(c,"click",K),Eb(c,!1),nb(c),k.push(c),ab||s(c,"contextmenu",
K),wb(c))):Ua(j,i)&&!ob(i)&&ka(h)&&(F&&m(c,"target",F),s(c,"click",qb),ab||s(c,"contextmenu",qb))}return k};dc=function(a){var b;b=lb(a);if(g("_mugicPopWin"))return g("_mugicPopWin")(b);K(a);return(F?h.open(b.href):h.open(b.href,F)).focus()};nb=function(a,b){var c,d,e,f,i;if(g("link_icon")||0<a.getAttribute("data-skim-product")&&g("skimwords_product_icon")){if(0<a.getElementsByTagName("img").length)return!0;if("msie"===n.browser&&8>n.version)a.style.display="inline-block";d=c="";null!=b&&(c=g("skimwords_icon_class",
""),d=g("skimwords_icon_link_class",""));i=m(a,"title").replace("'","&#39;");e=g("link_icon")||g("skimwords_product_icon");f=j.createElement("a");m(f,"href",m(a,"href"));m(f,"title",i);m(f,"style","border:0px;padding:0;margin:0");m(f,"skimlinked","skimlinked");m(f,"target","_blank");I(a,"skimlinks-unlinked")||I(a,"skimwords-link")?(m(f,"data-skim-creative",Oa(a,"skim-creative")),m(f,"data-group-id",Oa(a,"group-id")),m(f,"data-skimwords-word",Oa(a,"skimwords-word")),m(f,"data-skimwords-id",Oa(a,"skimwords-id")),
I(a,"skimlinks-unlinked")?m(f,"class","skimlinks-icon-link "+d+" skimlinks-unlinked"):m(f,"class","skimlinks-icon-link "+d+" skimwords-link")):(m(f,"data-skim-creative",""),m(f,"data-group-id",""),m(f,"data-skimwords-word",""),m(f,"data-skimwords-id",""),m(f,"class","skimlinks-icon-link "+d));d=j.createElement("img");m(d,"src",e);m(d,"class",c);m(d,"skimlinked","skimlinked");m(d,"style","margin: 0px 0px -3px 2px !important; float:none !important; border:0px; float:none !important; display:inline !important; width: auto !important; height: auto !important;");
f.appendChild(d);c=j.createElement("div");c.appendChild=f;c=c.childNodes[0];s(c,"mousedown",K);a.appendChild(f)}return!0};Wc=function(a,b){return null!=a.currentStyle?a.currentStyle[b]:h.getComputedStyle?j.defaultView.getComputedStyle(a,null).getPropertyValue(b):!1};ia=function(a,b){var c,d,e;for(d=0,e=b.length;d<e;d++)if(c=b[d],c===a)return!0;return!1};jc=function(a){var b,c,d,e;h.skimlinks_requests_in_flight-=1;a=null!=a?a:{};arguments.length&&(va.push(a),rb.publish("beacon",a));null!=h.skimlinks_runner&&
(h.skimlinks_runner.skimlinks=1);a.guid&&""===v&&(v=a.guid);a.sessid&&""===D&&(D=a.sessid);e=a.merchant_domains||[];for(c=0,d=e.length;c<d;c++)b=e[c],ma(b)||(x[b]=!0);for(b in x)null===x[b]&&(x[b]=!1);O&&(b=Y(),Ba=Nb(b),J+=Ba.length,!Qa&&"undefined"!==typeof ta&&null!==ta&&null!=y&&null!=y.domains&&(Qa=!0,ta(y.domains)),kc());ra||zc(a);return!0};Xb=function(a){return-1!==a.indexOf("#slm-")&&(a=a.split("#slm-"),2===a.length&&!isNaN(a[1])&&10*parseInt(a[1])===10*a[1])?parseInt(a[1]):null};Sb=function(a){var b,
c,d,e,f,i,k;a||(a=0);if(h.skimlinks_requests_in_flight&&5>a)setTimeout(function(){return Sb(a+1)},400*a);else{e=Y();c=0;for(i=0,k=e.length;i<k;i++)if(b=e[i],f=G(b.href),d=L(b.hostname),b=m(b,"class"),(!b||!(-1!==b.indexOf("skimwords-link")||-1!==b.indexOf("skimlinks-unlinked")))&&ja(f,d))if(b=Xb(f),$b(b)&&Tb(zb,Ab),Da(d)?(c++,q.hasOwnProperty(f)?q[f].ae=1:q[f]={count:0,ae:1}):q.hasOwnProperty(f)||(q[f]={count:0,ae:0}),q[f].count++,b)q[f].slmcid=b,0>sa.call(V,b)&&V.push(b);J=c;!Qa&&"undefined"!==typeof ta&&
null!==ta&&null!=y&&null!=y.domains&&(Qa=!0,ta(y.domains));kc()}return!0};kc=function(){"undefined"!==typeof eb&&null!==eb&&(wc||Ha)&&x.length&&eb();"undefined"!==typeof Ja&&null!==Ja&&Ja("skimlinks");return!0};Tb=function(a,b){var c;if(!a||!b)return!1;Bb=!0;h.adroll_adv_id=a;h.adroll_pix_id=b;h.__adroll_loaded=!0;c=j.createElement("script");c.setAttribute("async","true");c.type="text/javascript";c.src="//s.adroll.com/j/roundtrip.js";return j.getElementsByTagName("head").length?j.getElementsByTagName("head")[0].appendChild(c):
j.getElementsByTagName("script")[0].parentNode.appendChild(c)};ib=function(){var a,b,c,d,e,f,i;d=Y();c=[];for(f=0,i=d.length;f<i;f++)a=d[f],b=L(a.hostname),e=G(a.href),a=m(a,"rel"),b&&ja(e,b)&&ka(a)&&!ma(b)&&void 0===x[b]&&(c.push(b),y.domains.push(b),x[b]=null);return c};Kc=function(){var a;a=j.getElementsByTagName("body");if(0<a.length)return s(a[0],"click",ba),s(a[0],"contextmenu",ba)};ba=function(a){var b,c,d;if(h.event)a=h.event;c=a.originalTarget||a.srcElement||a.target;try{if("A"!==(null!=
c?c.nodeName.toUpperCase():void 0)&&c.parentNode)c=Ra(c)}catch(e){c=null}if(!c||Sa(c)||Wa(c)||!ka(m(c,"rel")))return!0;try{b=m(c,"sl-processed")||0,null==c["sl-processed"]&&(b=0)}catch(f){b=0}if((d=m(c,"class"))&&(-1!==d.indexOf("skimwords-link")||-1!==d.indexOf("skimlinks-inline")||-1!==d.indexOf("skimlinks-unlinked")))b=!0;if("A"===(null!=c?c.nodeName.toUpperCase():void 0)&&0===b)if(b=c,c=!0,!b||!b.href?c=!1:0!==b.href.indexOf("http://")&&0!==b.href.indexOf("https://")&&0!==b.href.indexOf("//")&&
(c=!1),c&&ja(b.href,L(b.hostname))){fc(b);if(g("vglnk")&&I(b,"skimwords-link"))a&&a.stopPropagation?a.stopPropagation():(a=h.event,a.cancelBubble=!0);return!0}};rc=function(a,b,c){if(0===b)return c;try{return a()}catch(d){return rc(a,b-1,c)}};Vc=function(a){if(null==a)return null;for(;"A"!==a.nodeName.toUpperCase();)if(a=rc(function(){return a.parentNode},3,null),null==a||Ta(a))return null;return a};Tc=function(a){var b,c;return cc&&(b=L(a.hostname),b in kb)?(b="[&?]"+kb[b].name+"=(http[^&]+)",decodeURIComponent(null!=
(c=a.href)?c.match(RegExp(b)).pop():void 0)||a.href):a.href};cd=function(a){return!a||!a.href||0!==a.href.indexOf("http://")&&0!==a.href.indexOf("https://")&&0!==a.href.indexOf("//")?!1:!0};hb=function(a){var b,c,d,e;if(h.event)a=h.event;b=a.originalTarget||a.srcElement||a.target;c=null!=b?b.nodeName.toUpperCase():void 0;"A"!==c&&"AREA"!==c&&(b=Vc(b));if(!b||Sa(b)||Wa(b)||!ka(m(b,"rel"))||ac(b))return!0;e=G(b.href);c=L(b.hostname);d="click"===a.type||"contextmenu"===a.type;if(cd(b)&&ja(b.href,c)){b.sl_hidden_domain&&
(c=L(b.sl_hidden_domain));if(pa&&Va(e))return!0;if(Da(c)||Va(e)||gd(c))hc(b,a);else if(d&&Ua(e,c)&&!ob(c))return F&&m(b,"target",F),qb(a);return!0}};fd=function(a,b){var c,d,e,f,i,k;null==b&&(b=mc);h.skimlinks_requests_in_flight=(null!=(c=h.skimlinks_requests_in_flight)?c:0)+1;if(!(null!=a&&a.length))return h[b](),!1;c=o('{"pubcode":"'+C+'","domains":_DOMAIN_LIST_,"page":"'+z.href+'"}');f="//r.skimresources.com/api/?callback="+b+(u?"&dnt="+u:"")+(M?"&fdnt=1":"")+(xc?"&call=toolbar":"")+"&data="+c;
c="msie"===n.browser?2E3:8E3;e=[];for(i=0,k=a.length;i<k;i++)d=a[i],e.push(d),f.replace("_DOMAIN_LIST_",o(r(e))).length>c&&(e=e.slice(0,-1));f=f.replace("_DOMAIN_LIST_",o(r(e)));return ha(f,!1,{})};wa=function(a){var b,c;b=[];oa&&(a.xrf=1);for(c in a)a.hasOwnProperty(c)&&b.push(""+c+"="+o(a[c]));return b.join("&")};Xa=function(a,b,c){var d,e,f;if("msie"!==n.browser)e=!1,f=new XMLHttpRequest,f.open("POST",a,!0),f.setRequestHeader("Content-type","application/x-www-form-urlencoded"),0<=sa.call(f,"withCredentials")&&
(f.withCredentials=!0),f.async="true",f.onreadystatechange=function(){var a;if(e)return!0;if(4===f.readyState){e=!0;if(200===f.status){a={};try{a=JSON.parse(f.responseText)}catch(b){try{a=eval("("+f.responseText+")")}catch(d){a={}}}c(a);return!0}return!1}},f.send(b);else if(h.XDomainRequest){if(d=new XDomainRequest,0<=sa.call(d,"withCredentials")&&(d.withCredentials=!0),d){d.open("POST",a,!0);d.onload=function(){var a;a={};if("undefined"!==typeof JSON&&null!==JSON&&JSON.parse)try{a=JSON.parse(d.responseText)}catch(b){a=
{}}else try{a=eval("("+d.responseText+")")}catch(e){a={}}c(a);return!0};d.onerror=function(){return!1};d.onprogress=function(){return!1};d.ontimeout=function(){return!1};d.async=!0;try{d.send(b)}catch(i){return!1}}}else return!1;return!0};Ya=function(a,b){var c;c={data:r({pubcode:C,domains:a,page:z.href})};wa(c);fd(a,b);return!0};pb=function(a){var b,c,d,e;c=[];for(d=0,e=a.length;d<e;d++)b=a[d],(null===x[b]||void 0===x[b])&&c.push(b);return c.length?Ya(c):!0};ec=function(){var a,b,c,d,e,f;c=Y();f=
[];for(d=0,e=c.length;d<e;d++)(a=c[d])&&a.href?(b=Ca(a.href),0>sa.call(Oc,b)?(m(a,"sl-processed",0),f.push(a["sl-processed"]=0)):f.push(void 0)):f.push(void 0);return f};Yb=function(){return"undefined"!==typeof aa&&null!==aa?"function"===typeof aa.init?aa.init(pd,Rc,Yc):void 0:void 0};yc=function(){if(h.skimlinksInitialized&&"function"!==typeof post_skimwords_hook)return!0;h.skimlinksInitialized=!0;bc();Yb();pa&&ec();uc&&!qa&&Kc();qa||(ib(),ra&&Ya(y.domains));"undefined"!==typeof ua&&null!==ua&&!ra&&
ua();"undefined"!==typeof skimwords&&null!==skimwords&&!Ia&&skimwords();return!0};dd=function(){if(xa)return!1;xa=!0;return yc()};hd=function(a){var b,c;b=0;for(c in a)E.call(a,c)&&(b+=1);return b};Eb=function(a,b){var c,d;d=a.style.cssText;""!==d&&(d+=" ");g("link_background")&&(c=g("link_background"),-1===c.indexOf("#")&&(c="#"+c),d+="background-color: "+c+" !important; ");if(null!==g("link_tooltip",null))a.title=g("link_tooltip");if(b){g("skimwords_color")&&(c=g("skimwords_color"),-1===c.indexOf("#")&&
(c="#"+c),d+="color: "+c+" !important; ");g("skimwords_weight")&&(d+="font-weight: "+g("skimwords_weight")+" !important; ");g("skimwords_decoration")&&(c=g("skimwords_decoration"),d="double"===c?d+"border-bottom: 1px double !important; ":"dashed"===c?d+"border-bottom: 1px dashed !important; ":d+("text-decoration: "+c+" !important; "));g("skimwords_style")&&(c=g("skimwords_style"),d+="font-style: "+c+" !important; ");g("skimwords_link_style")&&(c=g("skimwords_link_style"),d+=c+"; ");c=" "+a.className;
if(g("skimwords_link_class"))c+=" "+g("skimwords_link_class"),a.className=c.substring(1);if(null!==g("skimwords_title",null))a.title=g("skimwords_title");if(null===a.getAttribute("title"))a.title="Shopping link added by SkimWords";if(a.getAttribute("data-skim-creative")&&(c=parseInt(a.getAttribute("data-skim-creative"))%10,1===c||2===c))a.title=""}a.style.cssText=d;return!0};T=function(){return O?dd():Nc()};Mc=function(){var a;h.skimlinksInitialized=!0;Yb();pa&&ec();qa||(a=ib(),Ya(a),lc&&s(j,"mouseup",
hb,!0),s(j,"click",hb,!0),s(j,"contextmenu",hb,!0));return bc()};nd=function(a,b){var c,d,e,f,i;e=!1;if(Gb){d=Qc(a);0===d.length&&(e=!0);for(f=0,i=d.length;f<i;f++)if(c=d[f],0<=c.indexOf(b)){e=!0;break}}return e};Qc=function(a){var b,c,d,e;c=[];for(d=0,e=a.length;d<e;d++)b=a[d],b=b.replace(/https?\:\/\//,""),b=b.split("?")[0],c.push(b.split("#")[0]);return c};bc=function(){var a;a=nd(Gb,location.host+location.pathname);if(vc&&a&&"function"===typeof SkimPageIntelligence)return a="undefined"!==typeof Q&&
null!==Q?Q:"//t.skimresources.com/api/",Vb=SkimPageIntelligence({dataCollectionUrl:a+"dwelltime",pub:C,guid:v,uuid:H,sessid:D}),Vb.start()};Nc=function(){if(xa)return!1;xa=!0;return Ya(ib(),"skimlinksApplySecondaryHandlers")};ic=function(){return function(){return function(){var a,b,c;Jc();$d.detect(function(a){return X=a});if(g("skimlinks_revenue_forecast")&&g("skimlinks")||h.skimInitAlreadyCalled)return!1;O||Mc();b=function(){if(xa)return!0;try{j.documentElement.doScroll("left")}catch(a){return setTimeout(b,
50),!1}return T()};a=function(){return function(){return j.addEventListener?function(){j.removeEventListener("DOMContentLoaded",a,!1);T();return!0}:j.attachEvent?function(){j.detachEvent("onreadystatechange",a);T();return!0}:function(){T();return!0}}}(this)();if("complete"===j.readyState)setTimeout(T,1);else if(j.addEventListener)j.addEventListener("DOMContentLoaded",a,!1),h.addEventListener("load",T,!1);else if(j.attachEvent){j.attachEvent("onreadystatechange",a);h.attachEvent("onload",T);c=!1;try{c=
null===h.frameElement}catch(d){}j.documentElement.doScroll&&c&&b()}return h.skimInitAlreadyCalled=!0}}}(this)();Lc=function(a,b){return setTimeout(b,a)};h.skimlinksApplyHandlers=jc;h.skimlinksApplySecondaryHandlers=function(a){var b,c,d,e;h.skimlinks_requests_in_flight-=1;a=null!=a?a:{};arguments.length&&(va.push(a),rb.publish("beacon",a));null!=h.skimlinks_runner&&(h.skimlinks_runner.skimlinks=1);a.guid&&""===v&&(v=a.guid);a.sessid&&""===D&&(D=a.sessid);e=a.merchant_domains||[];for(c=0,d=e.length;c<
d;c++)b=e[c],ma(b)||(x[b]=!0);for(b in x)null===x[b]&&(x[b]=!1);"undefined"!==typeof ua&&null!==ua&&!ra&&ua();"undefined"!==typeof skimwords&&null!==skimwords&&!Ia&&skimwords();return Sb()};h.skimlinksApplyHandlersAlt=jc;h.skimlinksAjaxHandlerByClass=function(a){var b,c,d;if(O&&"function"===typeof j.getElementsByClassName){b=j.getElementsByClassName(a);for(c=0,d=b.length;c<d;c++)a=b[c],s(a,"click",ba),s(a,"contextmenu",ba);return!0}return!1};h.skimlinksAjaxHandlerById=function(a){return O&&(a=j.getElementById(a))?
(s(a,"click",ba),s(a,"contextmenu",ba),!0):!1};h.skimlinksRewriteUrl=Pb;h.skim_init=ic;!g("mugicPopWin")&&!g("skimlinks_legacy_support")&&!g("skimlinks_revenue_forecast")&&(h.mugicPopWin=K);!g("mugicRight")&&!g("skimlinks_legacy_support")&&!g("skimlinks_revenue_forecast")&&(h.mugicRight=K);h.skimlinksReload=function(){T();return!0};!g("skimlinks_legacy_support")&&!g("skimlinks_revenue_forecast")&&(h.skimlinks=yc);var rd,sd,Hb,Ac,fb,td,ud,vd,wd,xd,Bc,Ib,yd,zd,Ka,Ad,Bd,W,Cc,E={}.hasOwnProperty;Cc=W=
0;fb=!1;Ac=function(a){var b;return a&&-1!==a.indexOf("class=")?(b=a.match(/([^\[]+)\[class=([^\]]+)\]/i))&&3===b.length?b[1]+"."+b[2]:a:a};vd=function(a){Za[a]=Za[a]||0;Za[a]++;return a+"_"+Za[a]};Hb=function(a){var b,c,d;b=c=null;-1!==a.indexOf(".")?(a=a.split("."),d=a[0],b=a[1]):-1!==a.indexOf("[class=")?(a=a.split("[class="),d=a[0],b=a[1].split("]"),b=b[0]):-1!==a.indexOf("[class^=")?(a=a.split("[class^="),d=a[0],b=a[1].split("]"),b=b[0]):-1!==a.indexOf("[id*=")?(a=a.split("[id*="),d=a[0],c=a[1].split("]"),
c=c[0]):d=a;return{tag:d,id:c,"class":b}};Ib=function(a,b){var c,d,e,f,i,k;e=b.split(",");for(i=0,k=e.length;i<k;i++){b=e[i];b=G(b);b=Hb(b);f=!0;c=a.className||("function"===typeof a.getAttribute?a.getAttribute("class"):void 0)||"";d=("function"===typeof a.getAttribute?a.getAttribute("id"):void 0)||"";if(b.tag&&(!a.nodeName||a.nodeName.toLowerCase()!==b.tag))f=!1;if(b["class"]&&(!c||c!==b["class"]&&0!==c.indexOf(b["class"])))f=!1;if(b.id&&(!d||d!==b.id&&-1===d.indexOf(b.id)))f=!1;if(f)return!0}return!1};
ud=function(a){var b,c,d,e,f,i;if("undefined"!==typeof j.querySelectorAll)return j.querySelectorAll(a);e=[];a=Hb(a);if(a.tag&&a["class"]){d=j.getElementsByTagName(a.tag);for(f=0,i=d.length;f<i;f++)b=d[f],(c=b.className||b.getAttribute("class"))&&0===c.indexOf(a["class"])&&e.push(b)}else a.tag&&a.id?(b=j.getElementById(a.id))&&b.nodeName.toLowerCase()===a.tag&&e.push(b):(a=a.tag,e=j.getElementsByTagName(a));return e};wd=function(a,b,c){var d,e,f,i,k;d=[];if("undefined"!==typeof a.querySelectorAll)d=
a.querySelectorAll(b);else if(b=Hb(b),b.tag&&b["class"]){if(!a.getElementsByTagName)return c?[]:!1;f=a.getElementsByTagName(b.tag);for(i=0,k=f.length;i<k;i++)if(a=f[i],(e=a.className||a.getAttribute("class"))&&0===e.indexOf(b["class"]))if(c)d.push(a);else return!0}else if(b.tag&&b.id){if((a=j.getElementById(b.id))&&a.nodeName&&a.nodeName.toLowerCase()===b.tag)if(c)d.push(a);else return!0}else b=b.tag,d=a.getElementsByTagName(b);return c?d:0<d.length};Bc=function(a,b){return 0===b.length?!1:Ib(a,b.join(","))?
!0:a.parentNode?Bc(a.parentNode,b):!1};xd=function(a){var b;b=a.offsetWidth;a=a.offsetHeight;return 468===b&&60===a||234===b&&60===a||728===b&&90===a||300===b&&250===a||250===b&&250===a||336===b&&280===a||160===b&&600===a||120===b&&600===a?!0:!1};td=function(){var a;a=[];a.push("div.widget-content");a.push("div.googleAdText");a.push("div[id=ad]");a.push("div[id=banner]");a.push("div[id=advertisement]");a.push("div[id=adv_container]");a.push("div.ad");a.push("div.banner");a.push("div.advertisement");
a.push("div.ad_container");a.push("span.IL_AD");a.push("div[id=fave-ext-container]");a.push("span.skimlinks-unlinked");-1!==z.href.indexOf(".google.")?(a.push("td.gac_c"),a.push("table[id=mbEnd]"),a.push("div[id=mbEnd]"),a.push("span[id=taw]"),a.push("td.std"),a.push("div.std"),a.push("table.gssb_e"),a.push("div.c"),a.push("div[id=tads]")):-1!==z.href.indexOf(".yahoo.")?(a.push("ul.spns,ul.reducepx-spnslist"),a.push("ul[class*=reducepx-spnslist]"),a.push("ul[id=east]")):-1!==z.href.indexOf(".aol.")?
(a.push("div.sllLink"),a.push("div.n")):-1!==z.href.indexOf(".bing.")&&(a.push("div.sb_adsW"),a.push("div[id=sidebar]"),a.push("div.sb_adsWv2"),a.push("div.sb_adsNv2"),a.push("div[class*=sb_ads]"));return a};zd=function(a){var b,c,d,e;c={};for(d=0,e=a.length;d<e;d++)b=a[d],c[b]=!0;return c};Ka=function(){var a;a={};return{traverse:function(b,c,d,e){b=b||[];c=c||[];d=d||[];return a&&a.length&&!e?a:this.traverse_dom(b,c,d)},traverse_dom:function(b,c,d){var e,f,i,k,g,h,j,m;if(fb)return a;fb=!0;f=this.get_exclude_selector(c);
e=this.get_exclude_selector([]);c=f.selector;f=f.needed;e=e.selector;0===b.length&&b.push("body");b=b.concat(d);for(g=0,j=b.length;g<j;g++){i=b[g];i=Ac(i);i=ud(i);for(k=h=0,m=i.length;h<m;k=++h)k=i[k],this.traverse_node(k,f,e,c,d)}return a},traverse_node:function(b,c,d,e,f){var i,g;g=[];i=0;for(g.push({node:b,tagName:"",readOnly:!1,parent_id:null});i<g.length;){if((b=g[i].node)&&!xd(b)&&!la(b,"noskimwords",!0)&&(!c||!(""!==d&&Ib(b,d)))){g[i].readOnly=!1;if(b.nodeName&&b.nodeName!==cb){g[i].tagName=
b.nodeName;if(null!==g[i].parent_id)g[i].readOnly=g[g[i].parent_id].readOnly;if(!g[i].readOnly)if(c&&Ib(b,e))g[i].readOnly=!0;else if(ia(b.nodeName.toLowerCase(),f))g[i].readOnly=!0;if(ia(b.nodeName.toLowerCase(),f))g[i].readOnly=!0}else if(null!==g[i].parent_id)g[i].tagName=g[g[i].parent_id].tagName,g[i].readOnly=g[g[i].parent_id].readOnly;"msie"===n.browser&&9>n.version&&g[i].readOnly||(b.hasChildNodes()?g=this.add_child_nodes(g[i],i,g):this._add(b,!1,g[i].tagName,g[i].readOnly))}i++}return a},
is_traversed:function(){return fb},is_good_tag:function(a){return zd("p,body,div,span,ul,ol,li,table,tbody,td,tr,th,tfoot,col,colgroup,em,strong,big,small,blockquote,cite,b,dl,dfn,dd,dt,ins,form,legend,noframes,pre,noscript,center,font,i,article,section,main".split(","))[a.nodeName.toLowerCase()]?!0:!1},is_html:function(a){return(a=G(a))&&"<"===a[0]},get_non_colliding_nodes:function(){var b,c,d;d=a;c={};Cc=0;for(b in d)E.call(d,b)&&(c[b]=d[b],Cc++);return c},get_as_hash_node_dict:function(){var b,
c,d;c={};for(b in a)d=a[b],a.hasOwnProperty(b)&&(c[b]=d);return c},get_as_pair_array:function(){var b,c;c=[];for(b in a)E.call(a,b)&&c.push([b,a[b]]);return c},get_exclude_selector:function(a,c){var d,e,f,g,k,h;g=[];if(!c){c=j.getElementsByTagName("body");if(!c.length)return{needed:!1,selector:""};c=c[0]}a=a.concat(td());for(d=e=0,f=a.length;e<f;d=++e)a[d]=Ac(a[d]);e=!1;f="";for(k=0,h=a.length;k<h;k++)d=a[k],wd(c,d,!1)&&g.push(d);g.length&&(e=!0,f=g.join(",").replace("class=","class^="));return{needed:e,
selector:f}},length:function(){return hd(a)},reset:function(){a=[];return fb=!1},add_child_nodes:function(a,c,d){var e,f,g,k;k=a.node.childNodes;for(f=0,g=k.length;f<g;f++)(e=k[f])&&e.nodeName&&(this._add(e,!1,a.tagName,a.readOnly)||this.is_good_tag(e)&&d.push({node:e,tagName:a.tagName,readOnly:a.readOnly,parent_id:c}));return d},add_node:function(a,c){return this._add(a,c)},_add:function(b,c,d,e){var f;f=null;b.nodeName===cb&&(f=G(b.nodeValue));c=c||!1;if("msie"===n.browser&&9>n.version&&e)return!1;
if("msie"!==n.browser||9<=n.version)try{b.meta={ElementTag:d,ReadOnly:e}}catch(g){}if(f&&!this.is_html(f)&&3<=f.length){if(c&&"-1"===c)return!1;c=this._skim_id_hash(f,c);if(!c)return!1;a[c]=b}return f?!0:!1},_skim_id_hash:function(a){var c;if(!a)return"";c=G(a.replace(/\s+/g," ")).length;a=a.replace(/[:\s]*/g,"");c=""+c+":"+a.substring(0,20);return c=vd(c)}}}();Bd=function(a,b,c,d){var e,f,g,k,h,l,R,n,t,p,o;e=j.createDocumentFragment();R=0;n=[];o=b.nodeValue;k=[];h=b.parentNode;d||(d="skimwords-potential");
c||(c="-1");if(h){for(t=0,p=a.length;t<p;t++)g=a[t],l=j.createElement("span"),l.className=d,f=j.createTextNode(o.substring(R,g.start)),e.appendChild(f),l.innerHTML=g.text,e.appendChild(l),R={},R.node=l,R.match=g,m(R,"occurrence",g.target_occurrence),n.push(R),R=g.start+g.text.length,k.push(f),Ka.add_node(f,c);a=j.createTextNode(o.substring(R));k.push(a);e.appendChild(a);Ka.add_node(a,c);h.replaceChild(e,b)}return[n,k]};sd=function(a,b,c){var d,e,f;if(oa)return!1;d=(a.data?a.data:a.childNodes[0].data).replace(b.repl_regex,
b.replacement);f=j.createElement("span");b=j.createDocumentFragment();f.innerHTML=d;if("msie"===n.browser&&9>n.version&&(d=a.previousSibling,e=/^\s/,d&&d.nodeValue&&d.nodeValue.length&&e.test(d.nodeValue[d.nodeValue.length-1])&&(d.nodeValue+=" "),(d=a.nextSibling)&&d.nodeValue&&d.nodeValue.length&&e.test(d.nodeValue[0])))d.nodeValue=" "+d.nodeValue;for(;f.firstChild;)f.firstChild.nodeName===cb?(d=b.appendChild(f.firstChild),Ka.add_node(d)):(d=b.appendChild(f.firstChild),null!==d&&!c&&(Eb(d,!0),nb(d,
!0)));if(c=a.parentNode)return c.replaceChild(b,a)};yd=function(a,b){10>parseInt(b)&&(b="0"+b);return"3"+a+"0"+b};rd=function(a,b){1E7<a&&6!==b&&(a-=1E7);return a};Ad=function(a,b,c){var d,e,f;f=b.phrase;d={};d.w=f.text();d.lp=f.url();if(c)d.t=Dc,e="unlinked";else{if(0===f.limit())return!1;f.dec_limit();W+=1;d.ed=f.is_editor()?1:0;d.t=yd("02",f.action_type(),f.group_id());e="skimwords";d.pid=0===f.group_id()?0:rd(f.id(),f.action_type())}Cd(d,e);sd(a,b,c);return!0};var Dd,Ed,Fd,Gd,Hd,Id,zc,Jd,ua,Dc;
Dc="500005";Ed=function(a){s(a,"click",K);ab||s(a,"contextmenu",K);Eb(a,!1);return nb(a)};Id=function(a){a=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^\[\]\s]*\b|$/ig.exec(a);return a.length&&""!==a[0]?!0:!1};Gd=function(a,b,c,d){var e,f;e=Pa(a);f="";F&&(f='target="'+F+'"');b=mb(b);e="(?:^|[\\s]+)(?:\\\\;\\.|,\\'\\\"\\(\\)\\/:\\?])?("+e+")(?:\\'s)?(?:[\\\\;,\\.\\'\\\"|\\(\\)\\/:\\?])*(?:[\\s]+|$)";a='$1$2<a href="'+b+'" class="'+d+'" '+f+' data-skimwords-word="'+encodeURIComponent(mb(a))+
('"  data-skim-creative="'+c+'" title="">$3$4</a>$5$6');b=e.replace(/\?:/g,"");return{search_regex:RegExp(e,"i"),repl_regex:RegExp(b,"i"),repl_text:a}};Dd=function(){var a,b,c,d,e;b=Y("skimlinks-unlinked");e=[];for(c=0,d=b.length;c<d;c++)a=b[c],e.push(Ed(a));return e};zc=function(a){var b,c,d,e;b={};if((c=a.merchant_domains)&&c.length){for(d=0,e=c.length;d<e;d++)a=c[d],b[a]=!0;for(d=0,e=Fb.length;d<e;d++)c=Fb[d],a=c.match.domain,b.hasOwnProperty(a)&&Ad(c.node,c.match,!0)}Lc(10,function(){return Dd("skimlinks-unlinked")});
try{return Ja("unlinked")}catch(f){return!0}};Fd=function(a,b){var c,d,e,f,g,k,h,j,m,l,t;if(!a||Bc(a,["span.skimlinks-unlinked"]))return[[],[]];t=a.data;e=[];k=[];for(m=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^\[\]\s]*\b|$/ig;d=m.exec(t);)if(c=d[0],"link.phrase"!==c)if(g=d.index,0<G(c).length&&-1===c.indexOf("/.")&&-1===c.indexOf("..."))f=c,0!==c.indexOf("http")&&0!==c.indexOf("//")&&(f="msie"===n.browser&&6>=n.version?"http://"+c:"//"+c),d=Ca(f),j=Kd({OriginalPhrase:""+
c,Url:f,Title:"",ActionType:2,GroupId:0,Unlinked:!0}),(l=Gd(""+c,f,Dc,"skimlinks-unlinked"))&&k.push({start:g,text:""+mb(c),domain:d,repl_regex:l.repl_regex,replacement:l.repl_text,regex:l.search_regex,phrase:j,link:f}),e.push(d);else break;if(k.length){h=Bd(k,a,b,"skimlinks-unlinked");c=h[0];h=h[1];for(m=0,t=c.length;m<t;m++)k=c[m],Fb.push(k)}h||(h=[]);return[e,h]};Jd=function(a){var b,c,d;if(na.length)for(c=0,d=na.length;c<d;c++)if(b=na[c],b===a)return!1;if(Z.length){for(c=0,d=Z.length;c<d;c++)if(b=
Z[c],b===a)return!0;return!1}return!0};Hd=function(){var a,b,c,d,e,f,g;c=Ka.get_as_hash_node_dict();d={};for(b in c)if(a=c[b],a.parentNode&&!Wa(a)&&!la(a,"noskimwords")&&!la(a,"noskimlinks")&&!la(a,"noskimw")&&(!a.meta||!a.meta.ReadOnly)){a=Fd(a,b);g=a[0];for(e=0,f=g.length;e<f;e++)a=g[e],!d[a]&&Jd(a)&&(d[a]=!0,y.domains.push(a))}return y.domains.length?pb(y.domains):Ja("unlinked")};ua=function(){var a;a=j.getElementsByTagName("body");a.length?(a=a[0].textContent||a[0].innerText)&&Id(a)?Ia?(Ka.traverse([],
sc,[]),Hd()):getSkimwordsData("skimwordsSettingsCallback"):y.domains.length&&pb(y.domains):y.domains.length&&pb(y.domains)};h.skimlinksUnlinked=zc;var Ld,Jb,Md,Nd,p,La,Od,Kb,Pd,Qd,Rd,Sd,Td,eb,Ud,E={}.hasOwnProperty;p={pag:"",pub:"",guid:"",uc:"",lnks:{}};La={};Nd=function(a,b){var c,d,e;e="GBP"===a.currency?"&pound;":"EUR"===a.currency?"&euro;":"$";d=j.createElement("a");m(d,"href",a.url);m(d,"title",a.title);m(d,"target","_blank");Hc(d,"skimlinks-inline");m(d,"data-skim-creative",b);c=0;Ha&&(c=1);
m(d,"data-skimlinks-editor",c);c=parseFloat(Math.round(100*a.price)/100).toFixed(2);d.innerHTML=""+a.merchant+" "+e+c;s(d,"mousedown",K);return d};Md=function(a,b,c,d,e){return"8"+("text"===a?"1":"cross"===a?"2":"blink"===a?"3":"0")+b+c+(d-1)+e};Od=function(a,b){var c,d,e,f,g,h,j;c=b.price;if(!c)return"0";d=0;e=1E8;g=0;for(h=0,j=a.length;h<j;h++)f=a[h],f=parseFloat(f.price),f>d&&(d=f),parseFloat(f)<e&&(e=f),f===c&&g++;return 1<g?"4":c>=d?"3":c<=e?"1":"2"};Ud=function(a,b,c){var d,e,f,g,h;e=!1;for(d=
g=0,h=a.length;g<h;d=++g)if(f=a[d],f.url===c){e=d;break}e&&(c=a[e],"beginning"===b?(a[e]=a[0],a[0]=c):"end"===b&&(a[e]=a[a.length-1],a[a.length-1]=c));return a};Td=function(a){var b,c;if("1"===m(a,"ipc-added")){for(;")"!==(null!=(c=a.nextSibling)?c.textContent.substring(0,1):void 0);)(b=a.nextSibling)&&b.parentNode&&b.parentNode.removeChild(b);if(a&&a.parentNode&&a.nextSibling)return a.parentNode.removeChild(a.nextSibling)}};Ld=function(a,b,c,d,e,f,g){var k,l,n,p,o,t,w,q,r,s,v,u,x,y;Td(b);n=!0;o=
b;p=!1;c=Ud(c,pc,d);e.hasOwnProperty(d)?(t=e[d],f[t].cnt++):(g[d]={},t={},t.lpid=d,t.cnt=1,t.url=b.href.replace(ya,""),t.prd=[],t.ed=Ha?1:0,f.push(t),t=f.length-1,e[d]=t);"cross"===Ea?m(b,"style","text-decoration: line-through !important;"):"text"===Ea?null!=b.parentNode&&(e=null!=(q=Wc(b.parentNode,"color"))?q:"#000",m(b,"style","color: "+e+" !important; text-decoration: none !important;")):"blink"===Ea&&m(b,"style","text-decoration: blink !important;");e=c.length;q=0;if(h.skimlinks_editor)x=b.parentNode,
u=j.createElement("span"),v=j.createElement("span"),k=b.cloneNode(!0),u.appendChild(k),u.appendChild(v),u.style.display="inline !important",u.classList.add("sl-select-wrapper"),v.classList.add("sl-select-products"),k.classList.add("sl-select-link");for(k=0,y=c.length;k<y;k++){w=c[k];p=!0;s=w.currency+w.price+w.url+w.title+w.merchant;q+=1;l=Od(c,w);l=Md(Ea,l,e,a,q);if(!g[d].hasOwnProperty(s))r={},r.cur=w.currency,r.mn=w.merchant,r.mid=w.merchant_id,r.pr=w.price,r.ti=w.title,r.pu=w.url.replace(ya,""),
r.cr=l,f[t].prd.push(r),g[d][s]=!0;w=Nd(w,l);n?(s=j.createTextNode(" ("),n=!1):s=j.createTextNode(" | ");h.skimlinks_editor?(v.appendChild(s),v.appendChild(w)):(o.parentNode.insertBefore(s,o.nextSibling),s.parentNode.insertBefore(w,s.nextSibling));o=w}h.skimlinks_editor&&x.replaceChild(u,b);n||(a=j.createTextNode(") "),o.parentNode.insertBefore(a,o.nextSibling));m(b,"ipc-added",1);return p};Qd=function(a,b,c){var d,e;for(e in b)if(E.call(b,e)&&(d=b[e],e===a&&(0===d.length||ia(c,d))))return!0;return!1};
Jb=function(a){var b,c,d,e,f,g,h,j,l,n,o;if(!a)return!1;d={};e=[];g={};c=[];j=!1;for(l in a)if(E.call(a,l)&&La.hasOwnProperty(l)&&(h=a[l],h.length)){f=La[l];for(n=0,o=f.length;n<o;n++)b=f[n],l=G(b.href),m(b,"rel"),Ld(1,b,h,l,d,e,g)&&(j=!0),c.push({url:l,occurrence:m(b,"data-occurrence"),products:h})}j&&"undefined"!==typeof Lb&&null!==Lb&&Lb(e);"undefined"!==typeof setSelectLinks&&null!==setSelectLinks&&setSelectLinks(c);return!0};Pd=function(){var a;a="//ipc.skimresources.com/api/select_whitelist.php?callback=selectWhitelistCallback&data="+
o(r({pubcode:C,page:z.href}));return ha(a,!1,{},Kb,[])};Rd=function(a){var b,c,d,e,f,g;e="//ipc.skimresources.com/api/select.php?callback=selectCallback&urls=";b="msie"===n.browser?2E3:8E3;c=[];for(f=0,g=a.length;f<g;f++)d=a[f],c.push(d),d=o(r(c)).length,d+e.length>b&&(c=c.slice(0,-1));if(c.length)return e+=o(r(c)),ha(e,!1,{},Jb,!1)};Sd=function(a){var b;b={urls:r(a),debug:1};b=wa(b);(X||!Xa("//ipc.skimresources.com/api/select.php",b,Jb))&&Rd(a);return!0};Kb=function(a){var b,c,d,e,f,g,h,j,l,n,o,
p,q,r,s;if(!1!==a&&0===a.length)return!1;o=[];g={};h=Y();l=0;for(p=0,r=h.length;p<r;p++)if(b=h[p],e=L(b.hostname),n=G(b.href),j=m(b,"rel"),d=b.childNodes,!xb.length||ia(e,xb)){if(d&&d.length){f=!1;for(q=0,s=d.length;q<s;q++)c=d[q],c.nodeName&&"IMG"===c.nodeName.toUpperCase()&&(f=!0);if(f)continue}if(ja(n,e)&&ka(j)&&Da(e)&&(g.hasOwnProperty(n)||(g[n]=0),g[n]++,m(b,"data-occurrence",g[n]),m(b,"data-select-id",l),l++,!a||Qd(n,a,g[n])))if(c=m(b,"class"),!c||!(-1!==c.indexOf("skimlinks-inline")||-1!==
c.indexOf("skimwords-link")))if("undefined"===typeof La[n]&&(La[n]=[]),La[n].push(b),ia(n,o)||o.push(n),100<=o.length)break}return 0===o.length?!1:Sd(o)};eb=function(){return Ha?Pd():Kb(!1)};h.selectCallback=Jb;h.selectWhitelistCallback=Kb;h.skimlinksApplySelect=eb;var Kd;Kd=function(a){var b,c,d,e;d=b=null;c=5;a.Limit&&(c=a.Limit);e=function(){return a.Priority||0};return{group_id:function(){return b?b.id():0},dec_limit:function(){return c-1},limit:function(){return c},action_type:function(){return a.ActionType},
text:function(){return a.OriginalPhrase},start_byte:function(){return a.StartByte},url:function(){return a.Url},multi:function(){return a.Mt?!0:!1},is_editor:function(){return null!=a.ValidOn&&""!==a.ValidOn?!0:!1},is_blacklisted:function(){return null!=a.IsBlacklisted?a.IsBlacklisted:!1},group_priority:function(){return b?b.group_priority():e()},id:function(){return d?d:a.PhraseId},groups:function(){var b;return(b=a.Groups)?b:[]},title:function(){return a.Unlinked?"":null!=a.ActionTitle?a.ActionTitle:
"Shopping link provided by SkimWords"},set_title:function(b){return a.Unlinked?a.Title="":a.Title=b},occurrence:function(){return a.PhraseOccurrence},set_group:function(a){return b=a},set_id:function(a){return d=a}}};var Cd,gb,Vd,l,$,Q,Ec,Wd,Xd,Yd,Zd,qd,Ja,Lb,ta,Mb,Ma,E={}.hasOwnProperty;Q="//t.skimresources.com/api/";l={pag:"",phr:[],unl:[],pub:"",slc:0,swc:0,ulc:0,jsl:0,jsf:"",guid:"",uuid:"",sessid:"",uc:"",t:1,slmcid:!1};$={skimlinks:!0,skimwords:!0,unlinked:!0};Ma=0;Ec=!1;Cd=function(a,b){var c,
d,e,f;c=!0;if("skimwords"===b){for(e=0,f=fa.length;e<f;e++)if(d=fa[e],c=d.pid?d.pid===a.pid:d.w===a.w)return c;fa.push(a)}else if("unlinked"===b){for(e=0,f=ga.length;e<f;e++)d=ga[e],d.w===a.w&&(c=!1);c&&ga.push(a);Ma++}return c};Yd=function(){var a,b,c,d,e,f;a=8E3;"msie"===n.browser&&(a=2E3);d={};d.guid=v;d.uuid=H;d.sessid=D;d.pub=C;d.pag=z.href;d.tz=A;d.slmcid=V;d.dl={};d.typ="l";d.hae=J?1:0;c=""+Q+"link?data=";f=0;for(e in q)E.call(q,e)&&(b=q[e],f++,d.dl[e]=b,b=c+o(r(d)),b.length>a&&(f--,delete d.dl[e]));
f&&(c+=o(r(d)),ha(c,!1,{async:!0}));return!0};Wd=function(a){for(var b in a)if(E.call(a,b))return!1;return!0};ta=function(){var a;if(db||Wd(q))return!1;a={};a.guid=v;a.uuid=H;a.sessid=D;a.pub=C;a.pag=z.href;a.dl=q;a.tz=A;a.slmcid=V;a.typ="l";a.hae=J?1:0;a={data:r(a)};u&&(a.dnt=u);M&&(a.fdnt=1);a=wa(a);if(X||!Xa(""+Q+"link",a,Mb))return Yd()};qd=function(a){var b,c,d;b=g("pageTracker");d=g("urchinTracker");c="/"+bb+"/"+a;if(null!=b&&b._trackPageview)return b._trackPageview(c),!0;if(d)return d(c),!0;
g("_gaq")?(b=g("_gaq"),b.push(["_trackEvent",bb,"click",a])):g("ga")&&g("ga")("send","event","click",bb,a);return!1};Xd=function(a){var b,c,d,e,f;p.tz=A;p.guid=v;p.uuid=H;p.sessid=D;p.pref=P;p.lnks=[];p.typ="s";b=8E3;"msie"===n.browser&&(b=2E3);c=""+Q+"ipc?data=";for(e=0,f=a.length;e<f;e++)d=a[e],p.lnks.push(d),d=c+o(r(p)),d.length>b&&(p.lnks=p.lnks.slice(0,-1));p.lnks.length&&(c+=o(r(p)),ha(c,!1,{async:!0}));return!0};Lb=function(a){var b;if(db)return!1;p.tz=A;p.guid=v;p.uuid=H;p.sessid=D;p.pref=
P;p.lnks=a;p.typ="s";b={data:r(p)};b=wa(b);(X||!Xa(""+Q+"ipc",b,Mb))&&Xd(a);return!0};Mb=function(){return!0};Ja=function(a){var b,c;if(db||Ec)return!1;$[a]=!1;a=!0;for(b in $)if(E.call($,b)&&(c=$[b],!0===c)){a=!1;break}if(a)return Ec=!0,Vd()};gb=function(a){var b,c,d,e,f;if(a instanceof Array){c={};for(b=e=0,f=a.length;e<f;b=++e)d=a[b],c[""+b]=d;return c}return a};Zd=function(){var a,b,c,d,e;a=(new Date).getTime()-Wb;b=8E3;"msie"===n.browser&&(b=2E3);l.tz=A;l.slc=J;l.swc="undefined"!==typeof W&&
null!==W?W:0;l.ulc=null!=Ma?Ma:0;l.jsl=a;l.guid=v;l.slmcid=V;l.uuid=H;l.sessid=D;l.pref=P;l.phr=[];l.unl=[];oa&&(l.xrf=1);a=""+Q+"track.php?";u&&(a=a+"dnt="+u+"&");M&&(a+="fdnt=1&");X&&(a+="abp=1&");a+="data=";for(c=d=0,e=fa.length;d<e;c=++d)c=fa[c],l.phr.push(c),c=a+o(r(l).replace(ya,"")),c.length>b&&(l.phr=l.phr.slice(0,-1));for(c=d=0,e=ga.length;d<e;c=++d)c=ga[c],l.unl.push(c),c=a+o(r(l).replace(ya,"")),c.length>b&&(l.unl=l.unl.slice(0,-1));l.phr=gb(l.phr);l.unl=gb(l.unl);b=a+o(r(l).replace(ya,
""));ha(b,!1,{async:!0});return sb(1)};Vd=function(){var a;a=(new Date).getTime()-Wb;l.tz=A;l.slc=J;l.swc="undefined"!==typeof W&&null!==W?W:0;l.ulc=null!=Ma?Ma:0;l.jsl=a;l.guid=v;l.slmcid=V;l.uuid=H;l.sessid=D;l.pref=P;a=l;a.phr=gb(fa);a.unl=gb(ga);a={data:r(a)};u&&(a.dnt=u);M&&(a.fdnt=1);a=wa(a);if(X||!Xa(""+Q+"track.php",a,Mb))return Zd(),!0;null!=h.skimlinks_runner&&(h.skimlinks_runner.tracking=1);sb(1);return!0};var $d=new function(a){function b(a,c){e||1E3<c?"function"==typeof a&&(e?d?a(!0):
a(!1):a(!1)):setTimeout(b,c*=2,a,c)}function c(){e||(f.complete&&g.complete&&(e=!0),e&&"0"!=f.width&&"0"==g.width&&(d=!0))}var d=!1,e=!1,f=null,g=null;this.detect=function(a){b(a,250)};(function(){try{var b=navigator.userAgent.toLowerCase();if(-1==b.indexOf("firefox")&&-1==b.indexOf("chrome")){e=!0;d=!1;return}}catch(h){}b=11*Math.random();f=new Image;f.onload=c;f.src=a.replace(/\*/,1).replace(/\*/,b);g=new Image;g.onload=c;g.src=a.replace(/\*/,2).replace(/\*/,b)})()}("//p.skimresources.com/px.gif?ch=*&rn=*");
ic()})(this);
