#! /bin/sh
ECLIPSEDIR="${ECLIPSEDIR:-/var/lib/myfrdcsa/sandbox/eclipse-basic-20160110/eclipse-basic-20160110}"
LD_LIBRARY_PATH="$ECLIPSEDIR/lib/x86_64_linux:$LD_LIBRARY_PATH"
DAVINCIHOME="${DAVINCIHOME:-$ECLIPSEDIR/daVinci/x86_64_linux}"
JRE_HOME="${JRE_HOME:-/usr/lib/jvm/java-7-openjdk-amd64}"
export ECLIPSEDIR LD_LIBRARY_PATH DAVINCIHOME JRE_HOME
exec "/var/lib/myfrdcsa/sandbox/eclipse-basic-20160110/eclipse-basic-20160110/lib/x86_64_linux/eclipse.exe" "$@"
