read(gameDescriptionLanguageForRead_timeGames__ResearchPaper).
read(aPrivacyPreservingAlgorithmforMulti_AgentPlanningandSearch__ResearchArticle).
read(privacyPreservingPatternDatabases__ResearchArticle).
read(onInternallyDependentPublicActionsinMultiagentPlanning__ResearchArticle).
read(aSpatial_EpistemicLogicforReasoningaboutSecurityProtocols__ResearchPaper).
read(modalitiesForAccessControl_LogicsProof_TheoryAndApplications__Dissertation).

hasPrologCode(gameDescriptionLanguageForRead_timeGames__ResearchPaper,Code1).
hasPrologCode(modalitiesForAccessControl_LogicsProof_TheoryAndApplications__Dissertation,Code2).
