:- multifile addFeature/1, addFeatures/2, addHoursForLocation/1,
affiliatedWith/2, after/2, agent/3, agreedToFor/4, aka/3,
alsoKnownAs/2, anything/3, appointment/3, are/2, arg1Isa/2, arg2Isa/2,
arg3Isa/2, argument/3, ask/2, ask/3, askDoctorAbout/2, asserted/1,
at/2, atTime/2, ateCanOf/3, before/2, believe/2, believes/2,
bestByDate/2, billIssued/4, billIssued/4, billIssued/4, boycotting/2,
broken/1, cancelled/2, cancelled/2, cancelled/2, cap/1, capitalize/2,
catalystUserNameResolvesToAgent/2, categories/1, causes/2,
completed/1, connectedTo/2, consumers/2, convert/3,
coordinatesWithSeniorServices/1, costs/2, costs/3,
coterminalCondition/1, courseOfAction/1, coversTimePeriod/4,
coversTimePeriod/4, coversTimePeriod/4,
creaneedToScheduleAppointments/2, curGaeilgeArSeo/2, cycConstant/3,
cycMt/3, cycPredicate/3, cyc_constant_with_sigil/3,
cyc_constant_without_sigil/3, dateOfEvent/2, dayOfWeek/2, deadline/2,
depends/2, dependsCapabilityOnService/2, desires/1, desires/2,
desiresToWorkOn/2, dialogInterfaceQuery/3, dislikes/2, distance/3,
doExercises/3, doctor/1, dontDoExercise/3, emptyList/1, event/2,
event/3, eventually/1, expectedEventualSymptoms/2,
expectedTimeOfArrival/2, exportFromWSM/1, feelingMotivated/1, fgoal/1,
fixMe/1, fixme/1, fluents:cancelled/2, fluents:cancelled/2,
fluents:cancelled/2, fluents:hasAddress/2, fluents:hasEmail/2,
fluents:hasLocation/2, fluents:hasMeetingAgenda/2,
fluents:hasPhoneNumber/2, fluents:tasksAreAssignedByAgent/2,
fluents:tasksAreAssignedToAgent/2, formalizeThisProperly/1,
formalizeThisWithNLUMF/1, formula/3, forwardChaining/1,
generatePageFor/2, generatePageFor/3, genlsDirectlyList/2, goals/2,
goodIdea/1, habitual/1, habitualTasks/2, habituals/1, hadFall/2,
hasAbbreviation/2, hasAbility/2, hasAccount/2, hasAddress/2,
hasAlexaShoppingListItem/3, hasAmount/2, hasAppointment/3,
hasAvailableBalance/3, hasBalance/1, hasBarcode/2, hasBaseName/2,
hasBeliefSystems/2, hasBill/4, hasCapability/1, hasCapability/2,
hasCode/2, hasCost/2, hasDate/2, hasDescription/2, hasDirectory/2,
hasDistraction/2, hasDosage/2, hasDosage/3, hasEmail/2,
hasEmailAddress/2, hasEnglishGlossesData/2, hasExercise/2,
hasExercisePlan/5, hasExpectedTransaction/2, hasExpectedTransaction/3,
hasExpectedTransaction/3, hasExpectedTransaction/3, hasFacility/1,
hasFacility/1, hasFaxNumber/2, hasFirstName/2, hasFoodPreference/3,
hasFormalization/2, hasFormalization/3, hasHealthRisk/2,
hasHealthWorker/2, hasHoliday/3, hasHoliday/4, hasHours/3,
hasHoursSpec/3, hasHoursSpec2/2, hasInstruction/1, hasInstruction/1,
hasInstruction/1, hasInstruction/2, hasInsurance/2, hasInterest/2,
hasInventory/1, hasInventory/2, hasInventory/3, hasItem/2,
hasLastName/2, hasLocation/2, hasMedicalIssueToInvestigate/2,
hasMedicationAmount/5, hasMedicine/2, hasMeetingAgenda/2,
hasMixedConsistency/1, hasModelNumber/2, hasName/2,
hasNumberOfPorts/3, hasNumberOfSeniorCenters/2, hasObject/2,
hasPCIVideoCard/2, hasPayee/2, hasPercentage/2, hasPharmacy/2,
hasPhone/2, hasPhoneNumber/2, hasPositionalWeakness/1,
hasPrimaryEmail/2, hasProfession/2, hasProjects/2, hasProperty/2,
hasQuestion/2, hasQuestionFor/3, hasReasonForPackaging/2,
hasRecurrence/2, hasRecurrence/2, hasRecurrenceSpec/3, hasReference/2,
hasResource/2, hasResourceCenters/1, hasResources/1, hasResponse/3,
hasResponsibility/2, hasReward/2, hasSeason/2, hasService/1,
hasService/2, hasShoppingList/2, hasShoppingListItem/2,
hasShoppingListSupplier/1, hasSource/2, hasSpecialization/2,
hasStartDate/2, hasStrongConcern/2, hasSupplier/2, hasSymptom/2,
hasText/2, hasTrackingNumber/2, hasUrl/2, hasUseCase/2, hasUseCases/2,
hasWebsite/2, helps/1, highlyRecommended/1, incrCounter/2, init/2,
init_n/2, interactionCheck/4, inventorySourceOfItem/2,
isGratefulFor/2, isUsuallyEngagedInAtTime/3, isa/2, itemConsumed/2,
julian:form_time/3, levenshtein/3, likes/2, location/2, log/1, log/2,
loves/2, lower_case_list/2, mayCause/2, maybe/1, meeting/3, mfloat/3,
name/3, naturalLanguageQuery/2, needToScheduleAppointments/2, neg/1,
nonEmptyList/1, notFullyImplemented/1, number/3, on/2, oneOrMore/4,
output/2, overheardStatedPreference/1, packageAidsSystems/2, paid/5,
partiallyPerformsCapability/1, paymentPostedOnDate/2, periodically/1,
plan/3, planForContingency/1, plansToPlayWith/3, possible/1,
possibleResponse/2, possibleSourceOfFunds/1, potentialMoviesToWatch/2,
preferredTimesToBeReachedByPhone/2,
prefersAMessageToBeLeftByPhoneWhenNotAnsweringPhone/1, prevents/2,
prohibited/1, provides/2, purchased/2, purchased/3, purchased/4,
queryRef/3, questionHasNL/2, read_comment/2, read_file/2, read_line/1,
read_rest/2, read_word/3, reasonDescribedIn/1,
recommendedTimeToOccurBetween/3, repl/3, request/3, requestedInToDo/2,
requestsLoanToCover/2, said/2, said/3, scheduleAppointmentFor/3,
scheduleNextFamilyMeeting/0, scryList/2, see/1, seeAlso/1, sentence/3,
setLevel/1, shipping/2, shoppingList/1, should/1, softwareMetasite/1,
softwareMetasiteURL/1, someReasonsForPackaging/2, sometimes/1,
strategy/2, string/3, suggests/2, suitableRewardsFor/2, supplements/4,
takeToAppointment/3, takesSupplementFor/3, task/1, task/2, task/3,
taskAssignedByTo/3, taskIsAssignedByAgent/2, taskIsAssignedToAgent/2,
taskIsAssignedToSelf/2, tasksAreAssignedByAgent/2,
tasksAreAssignedToAgent/2, tasksAreOfferedByAgent/2,
tasksAreOfferedToAgent/2, tax/2, tell/3, tellDoctor/3,
thinksPossiblyHasIllness/2, timestampOfConsumption/2,
toDoListArgument/3, toDoListAssertionStatement/3, toDoListCommand/3,
toDoListConstant/3, toDoListFunctionSymbol/3, today/1, token/3,
unknown/1, unpreparedForContingency/1, usesOS/2, variable/3, verber/5,
view/1, when/2, work_on_S/5, work_on_T/4, worksFor/2, worksWith/2,
zeroOrMore/4, counter/2.

:- dynamic neg/1, planForContingency/1, instanceOf/2,
hasSomethingForPersonToDo/2, task/3, developResponsePlanFor/2,
possibleResponse/2, contingencyOccurred/1,
worstCaseDamageCriticality/2, unpreparedForContingency/1,
planForContingency/1, counter/2, currentDate/1, appointment/3,
deadline/2, hasStartDate/2, recommendedTimeToOccurBetween/3, task/3,
neg/1, hasSeason/2, hasSource/2, consumers/2, itemConsumed/2,
inventorySourceOfItem/2, timestampOfConsumption/2, electedPOTUS/1,
formalizeThisWithNLUMF/1, atTime/2, holds/2, currentPlanningCapsule/1.

